# Generated by Django 4.2.6 on 2023-12-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='null', upload_to='categories', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='inventario.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null', upload_to='products', verbose_name='Imagen'),
        ),
    ]
