# Generated by Django 4.2.5 on 2024-02-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_almacen_existencia_venta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existencia',
            options={'verbose_name': 'Existencia', 'verbose_name_plural': 'Existencias'},
        ),
        migrations.AlterField(
            model_name='article',
            name='id_Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.almacen'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
