from django.urls import path
from . import views

urlpatterns = [
    #path('punto-venta/', views.POS, name="Punto Venta"),
    path('punto-venta2/', views.POS, name="POS2"),
    path('clientes/', views.clientes_view, name="Clientes"),
    path('add_cliente/', views.add_cliente_view, name="AddCliente"),
    path('edit_cliente/<int:cliente_id>', views.add_cliente_view, name="EditCliente"),
    path('delete_cliente/<int:id>', views.delete_cliente_view, name="DeleteCliente"),
    path('productos/', views.productos_view, name="Productos"),
    path('delete_producto/<int:id>', views.delete_producto_view, name="DeleteProducto"),
    path('add_producto/', views.add_producto_view, name="AddProducto"),
    path('editar_producto/<int:producto_id>', views.add_producto_view, name="EditarProducto"),
    path('marca/', views.marca_view, name="Marca"),
    path('add_marca/', views.add_marca_view, name="AddMarca"),
    path('edit_marca/<int:marca_id>', views.add_marca_view, name="EditMarca"),
    path('delete_marca/<int:id>', views.delete_marca, name="DeleteMarca"),
    path('proveedor/', views.proveedor_view, name="Proveedor"),
    path('add_proveedor/', views.add_proveedor_view, name="AddProveedor"),
    path('edit_proveedor/<int:proveedor_id>', views.add_proveedor_view, name="EditProveedor"),
    path('delete_proveedor/<int:id>', views.delete_proveedor, name="DeleteProveedor"),
    path('familia/', views.familia_view, name="Familia"),
    path('add_familia/', views.add_familia_view, name="AddFamilia"),
    path('edit_familia/<int:familia_id>', views.add_familia_view, name="EditFamilia"),
    path('delete_familia/<int:id>', views.delete_familia, name="DeleteFamilia"),
    path('unidadmedida/', views.unidadmedida_view, name="UnidadMedida"),
    path('add_unidadmedida/', views.add_unidadmedida_view, name="AddUnidadMedida"),
    path('edit_unidadmedida/<int:unidadmedida_id>', views.add_unidadmedida_view, name="EditUnidadMedida"),
    path('delete_unidadmedida/<int:id>', views.delete_unidadmedida, name="DeleteUnidadMedida"),
    path('moneda/', views.moneda_view, name="Moneda"),
    path('add_moneda/', views.add_moneda_view, name="AddMoneda"),
    path('edit_moneda/<int:moneda_id>', views.add_moneda_view, name="EditMoneda"),
    path('delete_moneda/<int:id>', views.delete_moneda, name="DeleteMoneda"),
    path('tipo-cambio/', views.tipo_cambio_view, name="TipoCambio"),
    path('add_tipo-cambio/', views.add_tcambio_view, name="AddTipoCambio"),
    path('edit_tipo-cambio/<int:tcambio_id>', views.add_tcambio_view, name="EditTipoCambio"),
    path('delete_tipo-cambio/<int:id>', views.delete_tcambio, name="DeleteTipoCambio"),
    #path('actualizar_producto/<int:id>', views.actualizar_producto, name="ActualizarProducto"),
    #path('export/', views.export_pdf_view, name="ExportPDF" ),
    #path('export/<id>/<iva>', views.export_pdf_view, name="ExportPDF" ),
]
