# Generated by Django 4.2.6 on 2023-12-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dir_Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dir_Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='dir_Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cod_postal', models.IntegerField(blank=True, default='')),
                ('id_dirCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dir_ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='dir_ciudad',
            name='id_dirEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dir_estado'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13)),
                ('credito', models.BooleanField(default=False)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dias_credito', models.IntegerField(default=0)),
                ('lista_precios', models.IntegerField(default=1)),
                ('nombre_comercial', models.CharField(max_length=200, null=True)),
                ('dir_calle', models.CharField(max_length=200)),
                ('dir_numext', models.CharField(max_length=10)),
                ('dir_numint', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dir_idColonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dir_colonia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
