# Generated by Django 4.2.6 on 2023-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dir_idColonia',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dir_Ciudad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dir_Colonia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dir_Estado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dir_calle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
