# Generated by Django 4.2.6 on 2023-12-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cliente_dir_idcolonia_cliente_dir_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_Ciudad',
            new_name='dirCiudad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_Colonia',
            new_name='dirColonia',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_Estado',
            new_name='dirEstado',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_calle',
            new_name='dircalle',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_numext',
            new_name='dirnumext',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_numint',
            new_name='dirnumint',
        ),
    ]
