# Generated by Django 4.2.6 on 2023-12-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_egreso_productosegreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosegreso',
            name='egreso',
        ),
        migrations.RemoveField(
            model_name='productosegreso',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.DeleteModel(
            name='ProductosEgreso',
        ),
    ]
