# Generated by Django 4.2.5 on 2024-02-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_productosegreso_egreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('Unidad_Compras', models.IntegerField(default=0)),
                ('Unidad_Ventas', models.IntegerField(default=0)),
                ('Unidad_Inv', models.IntegerField(default=0)),
                ('cantidad_Unidad_Compras', models.IntegerField(default=0)),
                ('Cto_Unidad_Compras', models.DecimalField(decimal_places=4, max_digits=15)),
                ('Cto_Factura', models.DecimalField(decimal_places=4, max_digits=15)),
                ('Porc_GastosVarios', models.CharField(max_length=200, unique=True)),
                ('Porc_impuestos', models.CharField(max_length=200, unique=True)),
                ('Cto_Integrado', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
