# Generated by Django 4.2.5 on 2024-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productos_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Porc_impuestos',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
