# Generated by Django 4.2.5 on 2024-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productos_porc_impuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Compras',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Ventas',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
