# Generated by Django 4.2.5 on 2024-04-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_productos_unidad_compras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Porc_GastosVarios',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Porc_impuestos',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Inv',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
