# Generated by Django 4.2.5 on 2024-04-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productos_unidad_inv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Unidad_Inv',
        ),
        migrations.AddField(
            model_name='productos',
            name='Unidad_Inventario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Compras',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Ventas',
            field=models.CharField(default='', max_length=200),
        ),
    ]
