# Generated by Django 4.2.5 on 2024-05-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productos_codigo_bar_1_productos_codigo_bar_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=200),
        ),
    ]
