# Generated by Django 4.2.5 on 2024-06-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productos_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='codigo_bar_1',
            new_name='precioMN1',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='codigo_bar_2',
            new_name='precioMN2',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='codigo_bar_3',
            new_name='precioMN3',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='codigo_bar_4',
            new_name='precioMN4',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='codigo_bar_5',
            new_name='precioMN5',
        ),
    ]
