# Generated by Django 4.2.5 on 2024-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_codigo_bar_1_productos_preciomn1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='porc_util_1',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='porc_util_2',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='porc_util_3',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='porc_util_4',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='porc_util_5',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioMN1',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioMN2',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioMN3',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioMN4',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioMN5',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=15),
        ),
    ]
