# Generated by Django 4.2.5 on 2024-06-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_productos_porc_util_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='t_cambio',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=15),
        ),
    ]
