# Generated by Django 4.2.5 on 2024-06-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_proveedor_tipocambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='id_familia',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='id_marca',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='id_unidadmedida',
        ),
    ]
