# Generated by Django 4.2.5 on 2024-06-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_productos_unidad_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Inventario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Unidad_Ventas',
            field=models.IntegerField(),
        ),
    ]
