# Generated by Django 4.2.5 on 2024-07-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo_barras',
            field=models.CharField(default='', max_length=200),
        ),
    ]
