# Generated by Django 4.2.5 on 2024-08-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_tipo_cambio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_Cambio',
        ),
    ]
