# Generated by Django 4.2.5 on 2024-08-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_tipo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='tc_compra',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=8),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='tc_dof',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=8),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='tc_venta',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=8),
        ),
    ]
