# Generated by Django 4.2.5 on 2024-08-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_tipocambio_tc_compra_alter_tipocambio_tc_dof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocambio',
            name='tc_precios',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=8),
        ),
    ]
