# Generated by Django 4.2.5 on 2024-08-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_tipocambio_tc_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='t_cambio',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=8),
        ),
    ]
